In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
table_name = 'bronze.MG_District_Crime_News_Kumasi' 
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query = f"SELECT * FROM {table_name}"

# Execute the query and load the data into a DataFrame
df = pd.read_sql(query, engine)

In [3]:
pd.set_option('display.max_columns',None)
df.head(5)

,type,rank_group,rank_absolute,xpath,domain,title,url,image_url,snippet,time_published,timestamp,rectangle
0,news_search,1,1,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,gna.org.gh,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,https://api.dataforseo.com/cdn/i/07031430-8001...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",19 Oct 2023,2023-10-19 00:00:00 +00:00,None
1,news_search,2,2,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.asaaseradio.com,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,https://encrypted-tbn0.gstatic.com/images?q=tb...,The suspect made a second appearance before th...,18 Jan 2024,2024-01-18 00:00:00 +00:00,None
2,news_search,3,3,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.adomonline.com,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,https://api.dataforseo.com/cdn/i/07031430-8001...,Residents of Jirapa in the Upper West Region h...,1 month ago,2024-06-03 11:30:36 +00:00,None
3,news_search,4,4,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,dailyguidenetwork.com,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,https://encrypted-tbn0.gstatic.com/images?q=tb...,REPORTED CASES of violent crimes and other ill...,12 Dec 2023,2023-12-12 00:00:00 +00:00,None
4,news_search,5,5,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.bbc.com,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,https://api.dataforseo.com/cdn/i/07031430-8001...,Di domestic staff wey dey face accuse say e ki...,19 Sept 2023,2023-09-19 00:00:00 +00:00,None

In [4]:
df.drop(columns=['type', 'rank_group', 'rank_absolute', 'xpath','domain','image_url','rectangle'],axis=1,inplace=True)
df.head(5)

,title,url,snippet,time_published,timestamp
0,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",19 Oct 2023,2023-10-19 00:00:00 +00:00
1,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,The suspect made a second appearance before th...,18 Jan 2024,2024-01-18 00:00:00 +00:00
2,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,Residents of Jirapa in the Upper West Region h...,1 month ago,2024-06-03 11:30:36 +00:00
3,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,REPORTED CASES of violent crimes and other ill...,12 Dec 2023,2023-12-12 00:00:00 +00:00
4,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,Di domestic staff wey dey face accuse say e ki...,19 Sept 2023,2023-09-19 00:00:00 +00:00

In [5]:
df["timestamp"]=pd.to_datetime(df["timestamp"])
df["Date"]=df["timestamp"].dt.date

In [6]:
df.drop(columns=["time_published","timestamp"],axis=1,inplace=True)

In [7]:
df.head(5)

,title,url,snippet,Date
0,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",2023-10-19
1,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,The suspect made a second appearance before th...,2024-01-18
2,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,Residents of Jirapa in the Upper West Region h...,2024-06-03
3,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,REPORTED CASES of violent crimes and other ill...,2023-12-12
4,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,Di domestic staff wey dey face accuse say e ki...,2023-09-19

In [8]:
df["Region"]="Ashanti"

In [9]:
df.head(5)

,title,url,snippet,Date,Region
0,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",2023-10-19,Ashanti
1,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,The suspect made a second appearance before th...,2024-01-18,Ashanti
2,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,Residents of Jirapa in the Upper West Region h...,2024-06-03,Ashanti
3,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,REPORTED CASES of violent crimes and other ill...,2023-12-12,Ashanti
4,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,Di domestic staff wey dey face accuse say e ki...,2023-09-19,Ashanti

In [10]:
new_schema = 'silver'
new_table_name = 'MG_Crimes_Kumasi'

# Write DataFrame to the new table in the specified schema in the database
df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to silver.MG_Crimes_Kumasi successfully.