In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
table_name = 'bronze.MG_District_Crime_News_Accra' 
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query = f"SELECT * FROM {table_name}"

# Execute the query and load the data into a DataFrame
df = pd.read_sql(query, engine)

In [4]:
pd.set_option('display.max_columns',None)
df.head(5)

,type,rank_group,rank_absolute,xpath,domain,title,url,image_url,snippet,time_published,timestamp,rectangle
0,news_search,1,1,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.opendemocracy.net,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,https://encrypted-tbn0.gstatic.com/images?q=tb...,Rampant development and soaring property price...,27 Nov 2023,2023-11-27 00:00:00 +00:00,None
1,news_search,2,2,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,3news.com,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,https://api.dataforseo.com/cdn/i/07031433-8001...,The Achimota District Court has remanded four ...,1 month ago,2024-06-03 11:33:21 +00:00,None
2,news_search,3,3,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.ghanaweb.com,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,https://api.dataforseo.com/cdn/i/07031433-8001...,The Government of Canada has updated its Trave...,25 Jan 2024,2024-01-25 00:00:00 +00:00,None
3,news_search,4,4,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.adomonline.com,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,https://encrypted-tbn0.gstatic.com/images?q=tb...,The Ghana Police Service (GPS) is on a manhunt...,5 Oct 2023,2023-10-05 00:00:00 +00:00,None
4,news_search,5,5,/html[1]/body[1]/div[4]/div[1]/div[11]/div[1]/...,www.peacefmonline.com,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,https://api.dataforseo.com/cdn/i/07031433-8001...,One of the key suspects in the Ablekuma bullio...,16 Jul 2023,2023-07-16 00:00:00 +00:00,None

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   type            79 non-null     object
 1   rank_group      79 non-null     int64
 2   rank_absolute   79 non-null     int64
 3   xpath           79 non-null     object
 4   domain          79 non-null     object
 5   title           79 non-null     object
 6   url             79 non-null     object
 7   image_url       79 non-null     object
 8   snippet         79 non-null     object
 9   time_published  79 non-null     object
 10  timestamp       79 non-null     object
 11  rectangle       0 non-null      object
dtypes: int64(2), object(10)
memory usage: 7.5+ KB

In [6]:
df.columns

Index(['type', 'rank_group', 'rank_absolute', 'xpath', 'domain', 'title',
       'url', 'image_url', 'snippet', 'time_published', 'timestamp',
       'rectangle'],
      dtype='object')

In [9]:
df.drop(columns=['type', 'rank_group', 'rank_absolute', 'xpath','domain','image_url','rectangle'],axis=1,inplace=True)
df

,title,url,snippet,time_published,timestamp
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,27 Nov 2023,2023-11-27 00:00:00 +00:00
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,1 month ago,2024-06-03 11:33:21 +00:00
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,25 Jan 2024,2024-01-25 00:00:00 +00:00
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,5 Oct 2023,2023-10-05 00:00:00 +00:00
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,16 Jul 2023,2023-07-16 00:00:00 +00:00
...,...,...,...,...,...
74,Mass Promotion In Police Service,https://newsghana.com.gh/mass-promotion-in-pol...,Ghana Police Logo ONE HUNDRED-and forty-one po...,14 Mar 2012,2012-03-14 00:00:00 +00:00
75,Macbaron Hotel Manager Grabbed For Killing Clo...,https://newsghana.com.gh/macbaron-hotel-manage...,"DSP REYNOLDS Manteaw, Tema Community 1 Distric...",11 Dec 2012,2012-12-11 00:00:00 +00:00
76,10 Most Dangerous Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/most-dangero...,Learn about some of the most dangerous cities ...,10 Oct 2023,2023-10-10 00:00:00 +00:00
77,10 Safest Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/safest-citie...,Ghana is one of a few underappreciated tourist...,10 Oct 2023,2023-10-10 00:00:00 +00:00
78,"Uber & Bolt drivers, Tonaton & Jiji users blac...",https://www.mynewsgh.com/uber-bolt-drivers-ton...,"Teshie Nungua, a suburb of Accra has been blac...",15 Aug 2022,2022-08-15 00:00:00 +00:00

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           79 non-null     object
 1   url             79 non-null     object
 2   snippet         79 non-null     object
 3   time_published  79 non-null     object
 4   timestamp       79 non-null     object
dtypes: object(5)
memory usage: 3.2+ KB

In [11]:
df["timestamp"]=pd.to_datetime(df["timestamp"])

In [12]:
df.head(5)

,title,url,snippet,time_published,timestamp
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,27 Nov 2023,2023-11-27 00:00:00+00:00
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,1 month ago,2024-06-03 11:33:21+00:00
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,25 Jan 2024,2024-01-25 00:00:00+00:00
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,5 Oct 2023,2023-10-05 00:00:00+00:00
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,16 Jul 2023,2023-07-16 00:00:00+00:00

In [15]:
df["Date"]=df["timestamp"].dt.date

In [16]:
df

,title,url,snippet,time_published,timestamp,Date
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,27 Nov 2023,2023-11-27 00:00:00+00:00,2023-11-27
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,1 month ago,2024-06-03 11:33:21+00:00,2024-06-03
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,25 Jan 2024,2024-01-25 00:00:00+00:00,2024-01-25
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,5 Oct 2023,2023-10-05 00:00:00+00:00,2023-10-05
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,16 Jul 2023,2023-07-16 00:00:00+00:00,2023-07-16
...,...,...,...,...,...,...
74,Mass Promotion In Police Service,https://newsghana.com.gh/mass-promotion-in-pol...,Ghana Police Logo ONE HUNDRED-and forty-one po...,14 Mar 2012,2012-03-14 00:00:00+00:00,2012-03-14
75,Macbaron Hotel Manager Grabbed For Killing Clo...,https://newsghana.com.gh/macbaron-hotel-manage...,"DSP REYNOLDS Manteaw, Tema Community 1 Distric...",11 Dec 2012,2012-12-11 00:00:00+00:00,2012-12-11
76,10 Most Dangerous Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/most-dangero...,Learn about some of the most dangerous cities ...,10 Oct 2023,2023-10-10 00:00:00+00:00,2023-10-10
77,10 Safest Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/safest-citie...,Ghana is one of a few underappreciated tourist...,10 Oct 2023,2023-10-10 00:00:00+00:00,2023-10-10
78,"Uber & Bolt drivers, Tonaton & Jiji users blac...",https://www.mynewsgh.com/uber-bolt-drivers-ton...,"Teshie Nungua, a suburb of Accra has been blac...",15 Aug 2022,2022-08-15 00:00:00+00:00,2022-08-15

In [17]:
df.drop(columns=["time_published","timestamp"],axis=1,inplace=True)

In [18]:
df.head(5)

,title,url,snippet,Date
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,2023-11-27
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,2024-06-03
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,2024-01-25
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,2023-10-05
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,2023-07-16

In [19]:
df["Region"]="Accra"

In [20]:
df.head(5)

,title,url,snippet,Date,Region
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,2023-11-27,Accra
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,2024-06-03,Accra
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,2024-01-25,Accra
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,2023-10-05,Accra
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,2023-07-16,Accra

In [22]:
new_schema = 'silver'
new_table_name = 'MG_Crimes_Accra'

# Write DataFrame to the new table in the specified schema in the database
df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to silver.MG_Crimes_Accra successfully.