In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
table_name = 'bronze.MG_Churches_Kumasi' 
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query = f"SELECT * FROM {table_name}"

# Execute the query and load the data into a DataFrame
df = pd.read_sql(query, engine)

In [2]:
pd.set_option('display.max_columns', None)
df.head(5)

,type,rank_group,rank_absolute,domain,title,url,contact_url,hotel_rating,price_level,snippet,address,place_id,phone,main_image,total_photos,category,additional_categories,category_ids,feature_id,cid,latitude,longitude,is_claimed,local_justifications,is_directory_item,rating_rating_type,rating_value,rating_votes_count,rating_rating_max,rating_distribution_1,rating_distribution_2,rating_distribution_3,rating_distribution_4,rating_distribution_5,address_info_borough,address_info_address,address_info_city,address_info_zip,address_info_region,address_info_country_code,work_hours_timetable_sunday,work_hours_timetable_monday,work_hours_timetable_tuesday,work_hours_timetable_wednesday,work_hours_timetable_thursday,work_hours_timetable_friday,work_hours_timetable_saturday,work_hours_current_status,work_hours_timetable,rating,rating_distribution
0,maps_search,1,1,www.cccghana.org,Calvary Charismatic Centre (Headquarters),http://www.cccghana.org/,None,None,None,"Calvary Charismatic Centre, Ayigya, Kumasi","Calvary Charismatic Centre, Ayigya, Kumasi",ChIJs4nyylGU2w8R7q7U4rvJDBc,+233203322252,https://lh5.googleusercontent.com/p/AF1QipOCMq...,145.0,Pentecostal church,None,,0xfdb9451caf289b3:0x170cc9bbe2d4aeee,1660924171394526958,6.696211,-1.568178,False,,False,Max5,4.7,453.0,None,10.0,3.0,19.0,68.0,353.0,Tafo,"Calvary Charismatic Centre, Ayigya",Kumasi,None,None,GH,,,,,,,,open,None,None,None
1,maps_search,2,2,None,First Love Church Kumasi,None,None,None,None,"MFG8+86V, Unnamed Road, Kumasi","MFG8+86V, Unnamed Road, Kumasi",ChIJ0enkltWV2w8R_IlkBRUsz08,None,https://lh5.googleusercontent.com/p/AF1QipPiY2...,16.0,Church,None,,0xfdb95d596e4e9d1:0x4fcf2c15056489fc,5750863717971823100,6.675868,-1.534454,False,,False,Max5,4.7,34.0,None,2.0,0.0,0.0,1.0,31.0,None,"MFG8+86V, Unnamed Road",Kumasi,None,None,GH,,None,None,None,None,None,,close,None,None,None
2,maps_search,3,3,www.dclm.org,Deeper Life Bible Church - Kumasi South,http://www.dclm.org/,None,None,None,Kumasi,Kumasi,ChIJraPn2NOQ2w8Rfrqw9Ki5uHU,+233556951953,https://lh5.googleusercontent.com/p/AF1QipN20W...,28.0,Church,None,,0xfdb90d3d8e7a3ad:0x75b8b9a8f4b0ba7e,8482734033463196286,6.655635,-1.643769,True,,False,Max5,4.5,72.0,None,0.0,2.0,5.0,22.0,43.0,None,None,Kumasi,None,None,GH,,,,,,,,open,None,None,None
3,maps_search,4,4,None,Saint Peter's Cathedral Basilica,None,None,None,None,"M9VJ+XM Roman Hill, Kumasi","M9VJ+XM Roman Hill, Kumasi",ChIJZ8O6y_KW2w8RT4-_mdUqmRA,+233245766518,https://lh5.googleusercontent.com/p/AF1QipN3kI...,169.0,Catholic cathedral,,,0xfdb96f2cbbac367:0x10992ad599bf8f4f,1196034272939446095,6.695338,-1.617725,False,,False,Max5,4.4,360.0,None,14.0,12.0,30.0,74.0,230.0,Tafo,M9VJ+XM Roman Hill,Kumasi,None,None,GH,None,None,None,None,None,None,None,close,None,None,None
4,maps_search,5,5,None,St. George's Church,None,None,None,None,"M9RF+7FF, Fuller Road, Kumasi","M9RF+7FF, Fuller Road, Kumasi",ChIJbYIIoO-W2w8RupCfTCrg3-A,+233322029785,https://lh5.googleusercontent.com/p/AF1QipOuHh...,58.0,Church,None,,0xfdb96efa008826d:0xe0dfe02a4c9f90ba,16203916456581107898,6.690685,-1.626338,False,,False,Max5,4.2,77.0,None,1.0,1.0,15.0,22.0,38.0,None,"M9RF+7FF, Fuller Road",Kumasi,None,None,GH,None,None,None,None,None,None,None,close,None,None,None

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   type                            100 non-null    object
 1   rank_group                      100 non-null    int64
 2   rank_absolute                   100 non-null    int64
 3   domain                          13 non-null     object
 4   title                           100 non-null    object
 5   url                             13 non-null     object
 6   contact_url                     0 non-null      object
 7   hotel_rating                    0 non-null      object
 8   price_level                     0 non-null      object
 9   snippet                         100 non-null    object
 10  address                         100 non-null    object
 11  place_id                        100 non-null    object
 12  phone                           53 non-null     object
 13  main_image                      89 non-null     object
 14  total_photos                    88 non-null     float64
 15  category                        100 non-null    object
 16  additional_categories           5 non-null      object
 17  category_ids                    100 non-null    object
 18  feature_id                      100 non-null    object
 19  cid                             100 non-null    object
 20  latitude                        100 non-null    float64
 21  longitude                       100 non-null    float64
 22  is_claimed                      100 non-null    bool
 23  local_justifications            47 non-null     object
 24  is_directory_item               100 non-null    bool
 25  rating_rating_type              99 non-null     object
 26  rating_value                    99 non-null     float64
 27  rating_votes_count              99 non-null     float64
 28  rating_rating_max               0 non-null      object
 29  rating_distribution_1           99 non-null     float64
 30  rating_distribution_2           99 non-null     float64
 31  rating_distribution_3           99 non-null     float64
 32  rating_distribution_4           99 non-null     float64
 33  rating_distribution_5           99 non-null     float64
 34  address_info_borough            35 non-null     object
 35  address_info_address            97 non-null     object
 36  address_info_city               100 non-null    object
 37  address_info_zip                1 non-null      object
 38  address_info_region             0 non-null      object
 39  address_info_country_code       100 non-null    object
 40  work_hours_timetable_sunday     46 non-null     object
 41  work_hours_timetable_monday     37 non-null     object
 42  work_hours_timetable_tuesday    39 non-null     object
 43  work_hours_timetable_wednesday  44 non-null     object
 44  work_hours_timetable_thursday   40 non-null     object
 45  work_hours_timetable_friday     42 non-null     object
 46  work_hours_timetable_saturday   33 non-null     object
 47  work_hours_current_status       100 non-null    object
 48  work_hours_timetable            0 non-null      object
 49  rating                          0 non-null      object
 50  rating_distribution             0 non-null      object
dtypes: bool(2), float64(10), int64(2), object(37)
memory usage: 38.6+ KB

In [4]:
df.columns

Index(['type', 'rank_group', 'rank_absolute', 'domain', 'title', 'url',
       'contact_url', 'hotel_rating', 'price_level', 'snippet', 'address',
       'place_id', 'phone', 'main_image', 'total_photos', 'category',
       'additional_categories', 'category_ids', 'feature_id', 'cid',
       'latitude', 'longitude', 'is_claimed', 'local_justifications',
       'is_directory_item', 'rating_rating_type', 'rating_value',
       'rating_votes_count', 'rating_rating_max', 'rating_distribution_1',
       'rating_distribution_2', 'rating_distribution_3',
       'rating_distribution_4', 'rating_distribution_5',
       'address_info_borough', 'address_info_address', 'address_info_city',
       'address_info_zip', 'address_info_region', 'address_info_country_code',
       'work_hours_timetable_sunday', 'work_hours_timetable_monday',
       'work_hours_timetable_tuesday', 'work_hours_timetable_wednesday',
       'work_hours_timetable_thursday', 'work_hours_timetable_friday',
       'work_hours_timetable_saturday', 'work_hours_current_status',
       'work_hours_timetable', 'rating', 'rating_distribution'],
      dtype='object')

In [5]:
df.describe()

,rank_group,rank_absolute,total_photos,latitude,longitude,rating_value,rating_votes_count,rating_distribution_1,rating_distribution_2,rating_distribution_3,rating_distribution_4,rating_distribution_5
count,100.000000,100.000000,88.000000,100.000000,100.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
mean,50.500000,50.500000,27.284091,6.682511,-1.615480,4.449495,53.737374,1.767677,1.292929,5.747475,11.414141,33.515152
std,29.011492,29.011492,37.783396,0.023122,0.030553,0.341179,79.300203,2.743558,2.232654,8.441084,17.086222,52.535967
min,1.000000,1.000000,1.000000,6.607664,-1.683172,3.600000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25.750000,25.750000,4.000000,6.664602,-1.640327,4.300000,7.500000,0.000000,0.000000,0.000000,1.500000,4.000000
50%,50.500000,50.500000,15.000000,6.687629,-1.619865,4.400000,34.000000,1.000000,1.000000,3.000000,6.000000,21.000000
75%,75.250000,75.250000,32.000000,6.696305,-1.598010,4.700000,69.500000,2.000000,2.000000,8.000000,15.000000,40.500000
max,100.000000,100.000000,225.000000,6.736682,-1.534342,5.000000,495.000000,14.000000,14.000000,63.000000,117.000000,353.000000

In [6]:
df.drop(columns=['type', 'rank_group', 'rank_absolute','contact_url', 'hotel_rating', 'price_level', 'snippet','place_id','main_image', 'total_photos',
                    'additional_categories', 'category_ids', 'feature_id', 'cid','is_claimed', 'local_justifications','is_directory_item', 'rating_rating_type',
                    'rating_votes_count', 'rating_rating_max', 'rating_distribution_1','rating_distribution_2', 'rating_distribution_3','rating_distribution_4',
                    'rating_distribution_5','address_info_address', 'address_info_city','address_info_zip', 'address_info_region', 'address_info_country_code',
                    'work_hours_timetable_sunday', 'work_hours_timetable_monday','work_hours_timetable_tuesday', 'work_hours_timetable_wednesday','work_hours_timetable_thursday', 'work_hours_timetable_friday',
                    'work_hours_timetable_saturday', 'work_hours_current_status','work_hours_timetable', 'rating', 'rating_distribution'],axis=1,inplace=True)

In [7]:
df.head()

,domain,title,url,address,phone,category,latitude,longitude,rating_value,address_info_borough
0,www.cccghana.org,Calvary Charismatic Centre (Headquarters),http://www.cccghana.org/,"Calvary Charismatic Centre, Ayigya, Kumasi",+233203322252,Pentecostal church,6.696211,-1.568178,4.7,Tafo
1,None,First Love Church Kumasi,None,"MFG8+86V, Unnamed Road, Kumasi",None,Church,6.675868,-1.534454,4.7,None
2,www.dclm.org,Deeper Life Bible Church - Kumasi South,http://www.dclm.org/,Kumasi,+233556951953,Church,6.655635,-1.643769,4.5,None
3,None,Saint Peter's Cathedral Basilica,None,"M9VJ+XM Roman Hill, Kumasi",+233245766518,Catholic cathedral,6.695338,-1.617725,4.4,Tafo
4,None,St. George's Church,None,"M9RF+7FF, Fuller Road, Kumasi",+233322029785,Church,6.690685,-1.626338,4.2,None

In [8]:
df.drop(columns=["domain","url"],axis=1,inplace=True)

In [9]:
df

,title,address,phone,category,latitude,longitude,rating_value,address_info_borough
0,Calvary Charismatic Centre (Headquarters),"Calvary Charismatic Centre, Ayigya, Kumasi",+233203322252,Pentecostal church,6.696211,-1.568178,4.7,Tafo
1,First Love Church Kumasi,"MFG8+86V, Unnamed Road, Kumasi",None,Church,6.675868,-1.534454,4.7,None
2,Deeper Life Bible Church - Kumasi South,Kumasi,+233556951953,Church,6.655635,-1.643769,4.5,None
3,Saint Peter's Cathedral Basilica,"M9VJ+XM Roman Hill, Kumasi",+233245766518,Catholic cathedral,6.695338,-1.617725,4.4,Tafo
4,St. George's Church,"M9RF+7FF, Fuller Road, Kumasi",+233322029785,Church,6.690685,-1.626338,4.2,None
...,...,...,...,...,...,...,...,...
95,Kumasi Apostle Area,"M98M+8RM, Kumasi",+233244591004,Church,6.665848,-1.615456,4.3,None
96,The Access Church - Ghana,"P9P2+MWC, Abusuakruwa, Kumasi",+233244247813,Church,6.736682,-1.647744,4.3,Ampabame
97,Celestial Church Of Christ New Glory Parish,"M84X+4C6, Apire Rd, Kumasi",+233204358755,Church,6.655298,-1.651493,5.0,None
98,"Church Of Christ, Santasi - Kumasi","J9W4+X2H, Kumasi",None,Church of Christ,6.647447,-1.644903,5.0,None
99,Freeman Methodist Church Kumasi Kwadaso North,"P82W+J54, Kumasi",None,Methodist church,6.701524,-1.654535,5.0,Asuoyeboa

In [10]:
df.rename(columns={"title":"Name","address":"Address","phone":"Phone","category":"Category","latitude":"Latitude","longitude":"Longitude","rating_value":"Rating","address_info_borough":"Town"},inplace=True)

In [11]:
df.columns

Index(['Name', 'Address', 'Phone', 'Category', 'Latitude', 'Longitude',
       'Rating', 'Town'],
      dtype='object')

In [12]:
df.head(5)

,Name,Address,Phone,Category,Latitude,Longitude,Rating,Town
0,Calvary Charismatic Centre (Headquarters),"Calvary Charismatic Centre, Ayigya, Kumasi",+233203322252,Pentecostal church,6.696211,-1.568178,4.7,Tafo
1,First Love Church Kumasi,"MFG8+86V, Unnamed Road, Kumasi",None,Church,6.675868,-1.534454,4.7,None
2,Deeper Life Bible Church - Kumasi South,Kumasi,+233556951953,Church,6.655635,-1.643769,4.5,None
3,Saint Peter's Cathedral Basilica,"M9VJ+XM Roman Hill, Kumasi",+233245766518,Catholic cathedral,6.695338,-1.617725,4.4,Tafo
4,St. George's Church,"M9RF+7FF, Fuller Road, Kumasi",+233322029785,Church,6.690685,-1.626338,4.2,None

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Address    100 non-null    object
 2   Phone      53 non-null     object
 3   Category   100 non-null    object
 4   Latitude   100 non-null    float64
 5   Longitude  100 non-null    float64
 6   Rating     99 non-null     float64
 7   Town       35 non-null     object
dtypes: float64(3), object(5)
memory usage: 6.4+ KB

In [17]:
mean_values=df["Rating"].mean()
df["Rating"].fillna(mean_values)

0     4.7
1     4.7
2     4.5
3     4.4
4     4.2
     ...
95    4.3
96    4.3
97    5.0
98    5.0
99    5.0
Name: Rating, Length: 100, dtype: float64

In [18]:
df["Region"]="Ashanti"

In [19]:
import numpy as np
conditions = [
    df["Rating"] >= 4.0,
    (df["Rating"] >= 3.0) & (df["Rating"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
df["Rate"] = np.select(conditions, choices, default="Low")

In [20]:
df

,Name,Address,Phone,Category,Latitude,Longitude,Rating,Town,Region,Rate
0,Calvary Charismatic Centre (Headquarters),"Calvary Charismatic Centre, Ayigya, Kumasi",+233203322252,Pentecostal church,6.696211,-1.568178,4.7,Tafo,Ashanti,High
1,First Love Church Kumasi,"MFG8+86V, Unnamed Road, Kumasi",None,Church,6.675868,-1.534454,4.7,None,Ashanti,High
2,Deeper Life Bible Church - Kumasi South,Kumasi,+233556951953,Church,6.655635,-1.643769,4.5,None,Ashanti,High
3,Saint Peter's Cathedral Basilica,"M9VJ+XM Roman Hill, Kumasi",+233245766518,Catholic cathedral,6.695338,-1.617725,4.4,Tafo,Ashanti,High
4,St. George's Church,"M9RF+7FF, Fuller Road, Kumasi",+233322029785,Church,6.690685,-1.626338,4.2,None,Ashanti,High
...,...,...,...,...,...,...,...,...,...,...
95,Kumasi Apostle Area,"M98M+8RM, Kumasi",+233244591004,Church,6.665848,-1.615456,4.3,None,Ashanti,High
96,The Access Church - Ghana,"P9P2+MWC, Abusuakruwa, Kumasi",+233244247813,Church,6.736682,-1.647744,4.3,Ampabame,Ashanti,High
97,Celestial Church Of Christ New Glory Parish,"M84X+4C6, Apire Rd, Kumasi",+233204358755,Church,6.655298,-1.651493,5.0,None,Ashanti,High
98,"Church Of Christ, Santasi - Kumasi","J9W4+X2H, Kumasi",None,Church of Christ,6.647447,-1.644903,5.0,None,Ashanti,High
99,Freeman Methodist Church Kumasi Kwadaso North,"P82W+J54, Kumasi",None,Methodist church,6.701524,-1.654535,5.0,Asuoyeboa,Ashanti,High

In [21]:
df=df.reindex(columns=['Name', 'Address', 'Phone', 'Category', 'Latitude', 'Longitude',
       'Rating', 'Rate', 'Region', 'Town'])
df

,Name,Address,Phone,Category,Latitude,Longitude,Rating,Rate,Region,Town
0,Calvary Charismatic Centre (Headquarters),"Calvary Charismatic Centre, Ayigya, Kumasi",+233203322252,Pentecostal church,6.696211,-1.568178,4.7,High,Ashanti,Tafo
1,First Love Church Kumasi,"MFG8+86V, Unnamed Road, Kumasi",None,Church,6.675868,-1.534454,4.7,High,Ashanti,None
2,Deeper Life Bible Church - Kumasi South,Kumasi,+233556951953,Church,6.655635,-1.643769,4.5,High,Ashanti,None
3,Saint Peter's Cathedral Basilica,"M9VJ+XM Roman Hill, Kumasi",+233245766518,Catholic cathedral,6.695338,-1.617725,4.4,High,Ashanti,Tafo
4,St. George's Church,"M9RF+7FF, Fuller Road, Kumasi",+233322029785,Church,6.690685,-1.626338,4.2,High,Ashanti,None
...,...,...,...,...,...,...,...,...,...,...
95,Kumasi Apostle Area,"M98M+8RM, Kumasi",+233244591004,Church,6.665848,-1.615456,4.3,High,Ashanti,None
96,The Access Church - Ghana,"P9P2+MWC, Abusuakruwa, Kumasi",+233244247813,Church,6.736682,-1.647744,4.3,High,Ashanti,Ampabame
97,Celestial Church Of Christ New Glory Parish,"M84X+4C6, Apire Rd, Kumasi",+233204358755,Church,6.655298,-1.651493,5.0,High,Ashanti,None
98,"Church Of Christ, Santasi - Kumasi","J9W4+X2H, Kumasi",None,Church of Christ,6.647447,-1.644903,5.0,High,Ashanti,None
99,Freeman Methodist Church Kumasi Kwadaso North,"P82W+J54, Kumasi",None,Methodist church,6.701524,-1.654535,5.0,High,Ashanti,Asuoyeboa

In [22]:
new_schema = 'silver'
new_table_name = 'MG_Churches_Kumasi'

# Write DataFrame to the new table in the specified schema in the database
df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to silver.MG_Churches_Kumasi successfully.