In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
table_name = 'bronze.MG_Hospitals_Accra' 
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query = f"SELECT * FROM {table_name}"

# Execute the query and load the data into a DataFrame
df = pd.read_sql(query, engine)

In [2]:
pd.set_option('display.max_columns',None)
df.head(5)

,type,rank_group,rank_absolute,domain,title,url,contact_url,hotel_rating,price_level,snippet,address,place_id,phone,main_image,total_photos,category,additional_categories,category_ids,feature_id,cid,latitude,longitude,is_claimed,local_justifications,is_directory_item,rating_rating_type,rating_value,rating_votes_count,rating_rating_max,rating_distribution_1,rating_distribution_2,rating_distribution_3,rating_distribution_4,rating_distribution_5,address_info_borough,address_info_address,address_info_city,address_info_zip,address_info_region,address_info_country_code,work_hours_timetable_sunday,work_hours_timetable_monday,work_hours_timetable_tuesday,work_hours_timetable_wednesday,work_hours_timetable_thursday,work_hours_timetable_friday,work_hours_timetable_saturday,work_hours_current_status,work_hours_timetable
0,maps_search,1,1,None,Greater Accra Regional Hospital,None,None,None,None,"Castle Rd, Accra","Castle Rd, Accra",ChIJN5yfMHaa3w8RdnVUzz6HULQ,+233247814770,https://lh5.googleusercontent.com/p/AF1QipPrxk...,570.0,Hospital,None,,0xfdf9a76309f9c37:0xb450873ecf547576,12993033628800021878,5.561373,-0.198676,True,None,False,Max5,4.2,304,None,20,9,31,64,180,Osu Klottey,Castle Rd,Accra,None,None,GH,,,,,,,,open,None
1,maps_search,2,2,www.accramed.com,Accra Medical Centre,https://www.accramed.com/,None,None,None,"6 Angola Ln, Accra","6 Angola Ln, Accra",ChIJRRk7bIea3w8RF33vwFtUqmU,+233204096099,https://lh5.googleusercontent.com/p/AF1QipOo4m...,59.0,Hospital,None,,0xfdf9a876c3b1945:0x65aa545bc0ef7d17,7325760496927210775,5.568699,-0.186040,False,None,False,Max5,4.0,66,None,14,0,2,6,44,Osu Klottey,6 Angola Ln,Accra,None,None,GH,,,,,,,,open,None
2,maps_search,3,3,www.mabhospitals.org,MAB International Hospital,http://www.mabhospitals.org/,None,None,None,"Nii Kpakpa St, Accra","Nii Kpakpa St, Accra",ChIJbZmHn6mZ3w8Rw3Hvidjf1xY,+233209494300,https://lh5.googleusercontent.com/p/AF1QipMkHx...,50.0,Hospital,None,,0xfdf99a99f87996d:0x16d7dfd889ef71c3,1646030309947306435,5.601313,-0.256759,True,None,False,Max5,4.2,35,None,4,0,2,9,20,Okaikoi South,Nii Kpakpa St,Accra,None,None,GH,,,,,,,,open,None
3,maps_search,4,4,www.thetrusthospital.com,"Trust Specialist Hospital, Osu",http://www.thetrusthospital.com/,None,None,None,"1 Sunkwa Rd, Accra","1 Sunkwa Rd, Accra",ChIJvcQh4n-Q3w8RZnMUVR-1c4Y,+233302797147,https://lh5.googleusercontent.com/p/AF1QipOZhV...,98.0,Hospital,None,,0xfdf907fe221c4bd:0x8673b51f55147366,9688286369580086118,5.560744,-0.187220,True,None,False,Max5,4.3,48,None,3,0,5,13,27,Osu Klottey,1 Sunkwa Rd,Accra,None,None,GH,None,,,,,,,open,None
4,maps_search,5,5,www.kbth.gov.gh,Korle Bu Teaching Hospital,http://www.kbth.gov.gh/,None,None,None,"Guggisberg Ave, Accra","Guggisberg Ave, Accra",ChIJmcgvVTSX3w8RJq690GBuuXM,+233302739510,https://lh5.googleusercontent.com/p/AF1QipNNzF...,1012.0,Hospital,None,,0xfdf9734552fc899:0x73b96e60d0bdae26,8338817547151191590,5.536607,-0.226409,True,None,False,Max5,4.1,427,None,26,13,57,113,218,Ablekuma,Guggisberg Ave,Accra,None,None,GH,,,,,,,,open,None

In [4]:
df.drop(columns=['type', 'rank_group', 'rank_absolute','domain','contact_url', 'hotel_rating', 'price_level', 'snippet','place_id','main_image', 'total_photos',
                    'additional_categories', 'category_ids', 'feature_id', 'cid','is_claimed', 'local_justifications','is_directory_item', 'rating_rating_type',
                    'rating_votes_count', 'rating_rating_max', 'rating_distribution_1','rating_distribution_2', 'rating_distribution_3','rating_distribution_4',
                    'rating_distribution_5','address_info_address', 'address_info_zip', 'address_info_region', 'address_info_country_code',
                    'work_hours_timetable_sunday', 'work_hours_timetable_monday','work_hours_timetable_tuesday', 'work_hours_timetable_wednesday','work_hours_timetable_thursday', 'work_hours_timetable_friday',
                    'work_hours_timetable_saturday', 'work_hours_current_status','work_hours_timetable'],axis=1,inplace=True)

In [5]:
df.columns

Index(['title', 'url', 'address', 'phone', 'category', 'latitude', 'longitude',
       'rating_value', 'address_info_borough', 'address_info_city'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 100 non-null    object
 1   url                   47 non-null     object
 2   address               100 non-null    object
 3   phone                 94 non-null     object
 4   category              100 non-null    object
 5   latitude              100 non-null    float64
 6   longitude             100 non-null    float64
 7   rating_value          100 non-null    float64
 8   address_info_borough  86 non-null     object
 9   address_info_city     98 non-null     object
dtypes: float64(3), object(7)
memory usage: 7.9+ KB

In [7]:
df.head(5)

,title,url,address,phone,category,latitude,longitude,rating_value,address_info_borough,address_info_city
0,Greater Accra Regional Hospital,None,"Castle Rd, Accra",+233247814770,Hospital,5.561373,-0.198676,4.2,Osu Klottey,Accra
1,Accra Medical Centre,https://www.accramed.com/,"6 Angola Ln, Accra",+233204096099,Hospital,5.568699,-0.186040,4.0,Osu Klottey,Accra
2,MAB International Hospital,http://www.mabhospitals.org/,"Nii Kpakpa St, Accra",+233209494300,Hospital,5.601313,-0.256759,4.2,Okaikoi South,Accra
3,"Trust Specialist Hospital, Osu",http://www.thetrusthospital.com/,"1 Sunkwa Rd, Accra",+233302797147,Hospital,5.560744,-0.187220,4.3,Osu Klottey,Accra
4,Korle Bu Teaching Hospital,http://www.kbth.gov.gh/,"Guggisberg Ave, Accra",+233302739510,Hospital,5.536607,-0.226409,4.1,Ablekuma,Accra

In [8]:
df.rename(columns={"title":"Name","address":"Address","phone":"Phone","category":"Category","latitude":"Latitude","longitude":"Longitude","rating_value":"Rating","address_info_borough":"Town"},inplace=True)

In [9]:
df.head(5)

,Name,url,Address,Phone,Category,Latitude,Longitude,Rating,Town,address_info_city
0,Greater Accra Regional Hospital,None,"Castle Rd, Accra",+233247814770,Hospital,5.561373,-0.198676,4.2,Osu Klottey,Accra
1,Accra Medical Centre,https://www.accramed.com/,"6 Angola Ln, Accra",+233204096099,Hospital,5.568699,-0.186040,4.0,Osu Klottey,Accra
2,MAB International Hospital,http://www.mabhospitals.org/,"Nii Kpakpa St, Accra",+233209494300,Hospital,5.601313,-0.256759,4.2,Okaikoi South,Accra
3,"Trust Specialist Hospital, Osu",http://www.thetrusthospital.com/,"1 Sunkwa Rd, Accra",+233302797147,Hospital,5.560744,-0.187220,4.3,Osu Klottey,Accra
4,Korle Bu Teaching Hospital,http://www.kbth.gov.gh/,"Guggisberg Ave, Accra",+233302739510,Hospital,5.536607,-0.226409,4.1,Ablekuma,Accra

In [11]:
df.rename(columns={"address_info_city":"Region"},inplace=True)

In [12]:
import numpy as np
conditions = [
    df["Rating"] >= 4.0,
    (df["Rating"] >= 3.0) & (df["Rating"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
df["Rate"] = np.select(conditions, choices, default="Low")

In [13]:
df=df.reindex(columns=['Name', 'Address', 'Phone', 'Category', 'Latitude', 'Longitude',
       'Rating', 'Rate', 'Region', 'Town'])
df

,Name,Address,Phone,Category,Latitude,Longitude,Rating,Rate,Region,Town
0,Greater Accra Regional Hospital,"Castle Rd, Accra",+233247814770,Hospital,5.561373,-0.198676,4.2,High,Accra,Osu Klottey
1,Accra Medical Centre,"6 Angola Ln, Accra",+233204096099,Hospital,5.568699,-0.186040,4.0,High,Accra,Osu Klottey
2,MAB International Hospital,"Nii Kpakpa St, Accra",+233209494300,Hospital,5.601313,-0.256759,4.2,High,Accra,Okaikoi South
3,"Trust Specialist Hospital, Osu","1 Sunkwa Rd, Accra",+233302797147,Hospital,5.560744,-0.187220,4.3,High,Accra,Osu Klottey
4,Korle Bu Teaching Hospital,"Guggisberg Ave, Accra",+233302739510,Hospital,5.536607,-0.226409,4.1,High,Accra,Ablekuma
...,...,...,...,...,...,...,...,...,...,...
95,Iran Clinic,"Kojo Thompson Rd, Accra",+233302243342,Hospital,5.567997,-0.212504,3.8,Medium,Accra,Osu Klottey
96,St. John's Hospital & Fertility Centre,"Nsawam Road, Accra",+233501258518,Hospital,5.645333,-0.247638,4.1,High,Accra,Dome
97,Hanson Memorial Hospital,"HPJH+XGF, Accra",+233302304325,Hospital,5.582438,-0.271212,4.0,High,Accra,Ablekuma
98,Martin Memorial Hospital (Cardiovascular Centr...,"JQ6R+H4M, Sir Emmanuel Quist Street, Accra",+233241536281,Hospital,5.611467,-0.209715,5.0,High,Accra,Ayawaso
99,Rophi Hospital,Accra,+233208124185,Hospital,5.628301,-0.080343,3.2,Medium,Accra,None

In [15]:
df.Category.unique()

array(['Hospital', 'Government hospital', "Children's hospital",
       'Specialized hospital', 'University hospital', 'Medical Center'],
      dtype=object)

In [18]:
new_schema = 'silver'
new_table_name = 'MG_Hospitals_Accra'

# Write DataFrame to the new table in the specified schema in the database
df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to silver.MG_Hospitals_Accra successfully.