In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
hospitals_Kumasi = 'silver.SO_Hospitals_Kumasi'
hospitals_Accra = 'silver.MG_Hospitals_Accra'
Churches_Accra = 'silver.KS_Churches_Accra'
Churches_Kumasi = 'silver.MG_Churches_Kumasi'
Highschools_Kumasi = 'silver.MG_Highschools_Kumasi'
Highschools_Accra = 'silver.SA_Greater_Accra_High_School'
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query1 = f"SELECT * FROM {hospitals_Kumasi}"
query2 = f"SELECT * FROM {hospitals_Accra}"
query3 = f"SELECT * FROM {Churches_Accra}"
query4 = f"SELECT * FROM {Churches_Kumasi}"
query5 = f"SELECT * FROM {Highschools_Accra}"
query6 = f"SELECT * FROM {Highschools_Kumasi}"

# Execute the query and load the data into a DataFrame
hospitals_accra_df = pd.read_sql(query2, engine)
hospitals_kumasi_df = pd.read_sql(query1, engine)
churches_accra_df = pd.read_sql(query3, engine)
churches_kumasi_df = pd.read_sql(query4, engine)
highschools_accra_df = pd.read_sql(query5, engine)
highschools_kumasi_df = pd.read_sql(query6, engine)

In [2]:
hospitals_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Domain                          23 non-null     object
 1   Title                           103 non-null    object
 2   Rating_value                    99 non-null     float64
 3   Rating_votes_count              99 non-null     float64
 4   Address                         100 non-null    object
 5   Phone                           83 non-null     object
 6   Category                        100 non-null    object
 7   Latitude                        100 non-null    float64
 8   Longitude                       100 non-null    float64
 9   Address_info_address            73 non-null     object
 10  Address_info_city               100 non-null    object
 11  Address_info_country_code       100 non-null    object
 12  Work_hours_timetable_sunday     84 non-null     object
 13  Work_hours_timetable_monday     96 non-null     object
 14  Work_hours_timetable_tuesday    96 non-null     object
 15  Work_hours_timetable_wednesday  96 non-null     object
 16  Work_hours_timetable_thursday   95 non-null     object
 17  Work_hours_timetable_friday     96 non-null     object
 18  Work_hours_timetable_saturday   94 non-null     object
 19  Work_hours_timetable            0 non-null      object
 20  Region                          103 non-null    object
dtypes: float64(4), object(17)
memory usage: 17.0+ KB

In [3]:
hospitals_kumasi_df.drop(columns=["Domain","Rating_votes_count","Phone","Latitude","Longitude","Address_info_address","Address_info_city","Address_info_country_code",
                                  "Work_hours_timetable_sunday","Work_hours_timetable_monday","Work_hours_timetable_tuesday","Work_hours_timetable_wednesday",
                                  "Work_hours_timetable_thursday","Work_hours_timetable_friday","Work_hours_timetable_saturday","Work_hours_timetable"],axis=1,inplace=True)

In [4]:
hospitals_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         103 non-null    object
 1   Rating_value  99 non-null     float64
 2   Address       100 non-null    object
 3   Category      100 non-null    object
 4   Region        103 non-null    object
dtypes: float64(1), object(4)
memory usage: 4.2+ KB

In [5]:
import numpy as np
conditions = [
    hospitals_kumasi_df["Rating_value"] >= 4.0,
    (hospitals_kumasi_df["Rating_value"] >= 3.0) & (hospitals_kumasi_df["Rating_value"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
hospitals_kumasi_df["Rate"] = np.select(conditions, choices, default="Low")

In [6]:
hospitals_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Address    100 non-null    object
 2   Phone      94 non-null     object
 3   Category   100 non-null    object
 4   Latitude   100 non-null    float64
 5   Longitude  100 non-null    float64
 6   Rating     100 non-null    float64
 7   Rate       100 non-null    object
 8   Region     98 non-null     object
 9   Town       86 non-null     object
dtypes: float64(3), object(7)
memory usage: 7.9+ KB

In [7]:
hospitals_accra_df.drop(columns=["Phone","Latitude","Longitude",],axis=1,inplace=True)

In [8]:
hospitals_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      100 non-null    object
 1   Address   100 non-null    object
 2   Category  100 non-null    object
 3   Rating    100 non-null    float64
 4   Rate      100 non-null    object
 5   Region    98 non-null     object
 6   Town      86 non-null     object
dtypes: float64(1), object(6)
memory usage: 5.6+ KB

In [9]:
hospitals_accra_df.drop(columns=["Town"],axis=1,inplace=True)

In [10]:
hospitals_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      100 non-null    object
 1   Address   100 non-null    object
 2   Category  100 non-null    object
 3   Rating    100 non-null    float64
 4   Rate      100 non-null    object
 5   Region    98 non-null     object
dtypes: float64(1), object(5)
memory usage: 4.8+ KB

hospitals_kumasi_df.info()

In [11]:
churches_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Church_Name        100 non-null    object
 1   Church_Address     100 non-null    object
 2   Phone              74 non-null     object
 3   Category           100 non-null    object
 4   Latitude           100 non-null    float64
 5   Longitude          100 non-null    float64
 6   Rating             100 non-null    float64
 7   Town               96 non-null     object
 8   Region             100 non-null    object
 9   Work_Hours_Status  100 non-null    object
dtypes: float64(3), object(7)
memory usage: 7.9+ KB

In [12]:
churches_accra_df.drop(columns=["Phone","Latitude","Longitude","Town","Work_Hours_Status"],axis=1,inplace=True)

In [13]:
churches_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Church_Name     100 non-null    object
 1   Church_Address  100 non-null    object
 2   Category        100 non-null    object
 3   Rating          100 non-null    float64
 4   Region          100 non-null    object
dtypes: float64(1), object(4)
memory usage: 4.0+ KB

In [14]:
import numpy as np
conditions = [
    churches_accra_df["Rating"] >= 4.0,
    (churches_accra_df["Rating"] >= 3.0) & (churches_accra_df["Rating"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
churches_accra_df["Rate"] = np.select(conditions, choices, default="Low")

In [15]:
churches_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Address    100 non-null    object
 2   Phone      53 non-null     object
 3   Category   100 non-null    object
 4   Latitude   100 non-null    float64
 5   Longitude  100 non-null    float64
 6   Rating     99 non-null     float64
 7   Rate       100 non-null    object
 8   Region     100 non-null    object
 9   Town       35 non-null     object
dtypes: float64(3), object(7)
memory usage: 7.9+ KB

In [16]:
churches_kumasi_df.drop(columns=["Phone","Latitude","Longitude","Town"],axis=1,inplace=True)

In [17]:
churches_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      100 non-null    object
 1   Address   100 non-null    object
 2   Category  100 non-null    object
 3   Rating    99 non-null     float64
 4   Rate      100 non-null    object
 5   Region    100 non-null    object
dtypes: float64(1), object(5)
memory usage: 4.8+ KB

In [18]:
highschools_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         100 non-null    object
 1   Address       99 non-null     object
 2   Category      100 non-null    object
 3   Rating_value  99 non-null     float64
 4   Region        100 non-null    object
dtypes: float64(1), object(4)
memory usage: 4.0+ KB

In [19]:
highschools_accra_df.head()

,Title,Address,Category,Rating_value,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra

In [20]:
import numpy as np
conditions = [
    highschools_accra_df["Rating_value"] >= 4.0,
    (highschools_accra_df["Rating_value"] >= 3.0) & (highschools_accra_df["Rating_value"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
highschools_accra_df["Rate"] = np.select(conditions, choices, default="Low")

In [21]:
highschools_accra_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         100 non-null    object
 1   Address       99 non-null     object
 2   Category      100 non-null    object
 3   Rating_value  99 non-null     float64
 4   Region        100 non-null    object
 5   Rate          100 non-null    object
dtypes: float64(1), object(5)
memory usage: 4.8+ KB

In [22]:
highschools_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Address    99 non-null     object
 2   Phone      74 non-null     object
 3   Category   100 non-null    object
 4   Latitude   100 non-null    float64
 5   Longitude  100 non-null    float64
 6   Rating     100 non-null    float64
 7   Rate       100 non-null    object
 8   Region     100 non-null    object
 9   Town       36 non-null     object
dtypes: float64(3), object(7)
memory usage: 7.9+ KB

In [23]:
highschools_kumasi_df.drop(columns=["Phone","Latitude","Longitude","Town"],axis=1,inplace=True)

In [24]:
highschools_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      100 non-null    object
 1   Address   99 non-null     object
 2   Category  100 non-null    object
 3   Rating    100 non-null    float64
 4   Rate      100 non-null    object
 5   Region    100 non-null    object
dtypes: float64(1), object(5)
memory usage: 4.8+ KB

In [25]:
hospitals_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         103 non-null    object
 1   Rating_value  99 non-null     float64
 2   Address       100 non-null    object
 3   Category      100 non-null    object
 4   Region        103 non-null    object
 5   Rate          103 non-null    object
dtypes: float64(1), object(5)
memory usage: 5.0+ KB

In [26]:
hospitals_kumasi_df.rename(columns={"Rating_value":"Rating","Title":"Name"},inplace=True)

In [27]:
hospitals_kumasi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      103 non-null    object
 1   Rating    99 non-null     float64
 2   Address   100 non-null    object
 3   Category  100 non-null    object
 4   Region    103 non-null    object
 5   Rate      103 non-null    object
dtypes: float64(1), object(5)
memory usage: 5.0+ KB

In [28]:
hospitals_kumasi_df.head(5)

,Name,Rating,Address,Category,Region,Rate
0,Mount Zion Hospital,5.0,None,None,Ashanti Region,High
1,Komfo Anokye Teaching Hospital,4.1,"Okomfo Anokye Road, Kumasi",Hospital,Ashanti Region,High
2,Kumasi South Hospital,3.7,"MC27+GC3, Kumasi",Hospital,Ashanti Region,Medium
3,Asafo-Boakye Specialist Hospital,4.4,"10 Dr Asafo Boakye St, Kumasi",Hospital,Ashanti Region,High
4,Adiebeba Hospital,4.3,"4 Melcom Road, Kumasi",Hospital,Ashanti Region,High

In [29]:
hospitals_kumasi_df=hospitals_kumasi_df.reindex(columns=['Name', 'Address', 'Category','Rating', 'Rate', 'Region'])
hospitals_kumasi_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Mount Zion Hospital,None,None,5.0,High,Ashanti Region
1,Komfo Anokye Teaching Hospital,"Okomfo Anokye Road, Kumasi",Hospital,4.1,High,Ashanti Region
2,Kumasi South Hospital,"MC27+GC3, Kumasi",Hospital,3.7,Medium,Ashanti Region
3,Asafo-Boakye Specialist Hospital,"10 Dr Asafo Boakye St, Kumasi",Hospital,4.4,High,Ashanti Region
4,Adiebeba Hospital,"4 Melcom Road, Kumasi",Hospital,4.3,High,Ashanti Region

In [30]:
hospitals_accra_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Greater Accra Regional Hospital,"Castle Rd, Accra",Hospital,4.2,High,Accra
1,Accra Medical Centre,"6 Angola Ln, Accra",Hospital,4.0,High,Accra
2,MAB International Hospital,"Nii Kpakpa St, Accra",Hospital,4.2,High,Accra
3,"Trust Specialist Hospital, Osu","1 Sunkwa Rd, Accra",Hospital,4.3,High,Accra
4,Korle Bu Teaching Hospital,"Guggisberg Ave, Accra",Hospital,4.1,High,Accra

In [31]:
churches_accra_df.head(5)

,Church_Name,Church_Address,Category,Rating,Region,Rate
0,C3 Hope City Church Accra,"Asoyi Crescent, La-Bawaleshi Rd, Accra",Church,4.8,Greater Accra,High
1,Ridge Church,Accra,Non-denominational church,4.5,Greater Accra,High
2,Elim International Family Church,"MV82+7P6, Accra",Church,4.7,Greater Accra,High
3,"International Church of Christ, Accra","HV96+X4F, Accra",Church of Christ,5.0,Greater Accra,High
4,St. Paul's Roman Catholic Church,"HQPP+48F, Accra",Catholic church,4.5,Greater Accra,High

In [32]:
churches_accra_df.rename(columns={"Church_Name":"Name","Church_Address":"Address"},inplace=True)
churches_accra_df=churches_accra_df.reindex(columns=['Name', 'Address', 'Category','Rating', 'Rate', 'Region'])
churches_accra_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,C3 Hope City Church Accra,"Asoyi Crescent, La-Bawaleshi Rd, Accra",Church,4.8,High,Greater Accra
1,Ridge Church,Accra,Non-denominational church,4.5,High,Greater Accra
2,Elim International Family Church,"MV82+7P6, Accra",Church,4.7,High,Greater Accra
3,"International Church of Christ, Accra","HV96+X4F, Accra",Church of Christ,5.0,High,Greater Accra
4,St. Paul's Roman Catholic Church,"HQPP+48F, Accra",Catholic church,4.5,High,Greater Accra

In [33]:
churches_kumasi_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Calvary Charismatic Centre (Headquarters),"Calvary Charismatic Centre, Ayigya, Kumasi",Pentecostal church,4.7,High,Ashanti
1,First Love Church Kumasi,"MFG8+86V, Unnamed Road, Kumasi",Church,4.7,High,Ashanti
2,Deeper Life Bible Church - Kumasi South,Kumasi,Church,4.5,High,Ashanti
3,Saint Peter's Cathedral Basilica,"M9VJ+XM Roman Hill, Kumasi",Catholic cathedral,4.4,High,Ashanti
4,St. George's Church,"M9RF+7FF, Fuller Road, Kumasi",Church,4.2,High,Ashanti

In [34]:
highschools_kumasi_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,St Louis Senior High School,Kumasi,High school,4.4,High,Ashanti
1,Asanteman Senior High,Kumasi,School,4.2,High,Ashanti
2,Osei Tutu Senior High School,"Akropong, Kumasi",High school,4.4,High,Ashanti
3,Nkawie Senior High Technical School,"Nkawie Rd, Kumasi",Technical,4.2,High,Ashanti
4,Adu Gyamfi Senior High School,"Road, Gyamase",School,4.3,High,Ashanti

In [35]:
highschools_accra_df.head(5)

,Title,Address,Category,Rating_value,Region,Rate
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra,High
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra,High
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra,High
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra,High
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra,High

In [36]:
highschools_accra_df=highschools_accra_df

In [37]:
highschools_accra_df.head(5)

,Title,Address,Category,Rating_value,Region,Rate
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra,High
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra,High
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra,High
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra,High
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra,High

In [38]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
Highschools_Accra = 'silver.SA_Greater_Accra_High_School'
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query = f"SELECT * FROM {Highschools_Accra}"

# Execute the query and load the data into a DataFrame
df = pd.read_sql(query, engine)

In [39]:
df.head(5)

,Title,Address,Category,Rating_value,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra

In [40]:
highschools_accra_df=df

In [41]:
highschools_accra_df.head(5)

,Title,Address,Category,Rating_value,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra

In [42]:
import numpy as np
conditions = [
    highschools_accra_df["Rating_value"] >= 4.0,
    (highschools_accra_df["Rating_value"] >= 3.0) & (highschools_accra_df["Rating_value"] < 4.0)
]

choices = [
    "High",
    "Medium"
]

# Apply conditions using numpy select
highschools_accra_df["Rate"] = np.select(conditions, choices, default="Low")

In [43]:
highschools_accra_df.head(5)

,Title,Address,Category,Rating_value,Region,Rate
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,Greater Accra,High
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,Greater Accra,High
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,Greater Accra,High
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,Greater Accra,High
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,Greater Accra,High

In [44]:
highschools_accra_df.rename(columns={"Title":"Name","Rating_value":"Rating"},inplace=True)
highschools_accra_df=highschools_accra_df.reindex(columns=['Name', 'Address', 'Category','Rating', 'Rate', 'Region'])
highschools_accra_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra

In [45]:
amenities_df=pd.concat([highschools_accra_df,highschools_kumasi_df,churches_accra_df,churches_kumasi_df,hospitals_accra_df,hospitals_kumasi_df])
amenities_df.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra

In [46]:
amenities_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 603 entries, 0 to 102
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      603 non-null    object
 1   Address   598 non-null    object
 2   Category  600 non-null    object
 3   Rating    597 non-null    float64
 4   Rate      603 non-null    object
 5   Region    601 non-null    object
dtypes: float64(1), object(5)
memory usage: 33.0+ KB

In [47]:
amenities_df.Region.unique()

array([' Greater Accra', 'Ashanti', 'Greater Accra', 'Accra', 'Achimota',
       'Lapaz', 'Swanlake', None, 'Madina', 'Lashibi', 'Tsuibleoo',
       'Powerland', 'Mallam', 'Adenta Municipality', 'Obuasi',
       'Ashanti Region'], dtype=object)

In [48]:
df1=amenities_df

In [49]:
df1.head(5)

,Name,Address,Category,Rating,Rate,Region
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra

In [50]:
amenities_df.loc[amenities_df["Region"] == "Ashanti", "Region"] = "Ashanti Region"

In [51]:
amenities_df.Region.unique()

array([' Greater Accra', 'Ashanti Region', 'Greater Accra', 'Accra',
       'Achimota', 'Lapaz', 'Swanlake', None, 'Madina', 'Lashibi',
       'Tsuibleoo', 'Powerland', 'Mallam', 'Adenta Municipality',
       'Obuasi'], dtype=object)

In [52]:
amenities_df.loc[amenities_df["Region"] == " Greater Accra", "Region"] = "Greater Accra Region"

In [53]:
amenities_df.loc[amenities_df["Region"] == "Accra", "Region"] = "Greater Accra Region"

In [54]:
amenities_df.loc[amenities_df["Region"] == "Achimota", "Region"] = "Greater Accra Region"

In [55]:
amenities_df.loc[amenities_df["Region"] == "Lapaz", "Region"] = "Greater Accra Region"

In [56]:
amenities_df.loc[amenities_df["Region"] == "Swanlake", "Region"] = "Greater Accra Region"

In [57]:
amenities_df.loc[amenities_df["Region"] == "Madina", "Region"] = "Greater Accra Region"

In [58]:
amenities_df.loc[amenities_df["Region"] == "Lashibi", "Region"] = "Greater Accra Region"

In [59]:
amenities_df.loc[amenities_df["Region"] == "Tsuibleoo", "Region"] = "Greater Accra Region"

In [60]:
amenities_df.loc[amenities_df["Region"] == "Powerland", "Region"] = "Greater Accra Region"

In [61]:
amenities_df.loc[amenities_df["Region"] == "Mallam", "Region"] = "Greater Accra Region"

In [62]:
amenities_df.loc[amenities_df["Region"] == "Adenta Municipality", "Region"] = "Greater Accra Region"

In [63]:
amenities_df.loc[amenities_df["Region"] == "Obuasi", "Region"] = "Ashanti Region"

In [64]:
amenities_df.Region.unique()

array(['Greater Accra Region', 'Ashanti Region', 'Greater Accra', None],
      dtype=object)

In [65]:
amenities_df.loc[amenities_df["Region"] == "Greater Accra", "Region"] = "Greater Accra Region"

In [66]:
amenities_df.Region.unique()

array(['Greater Accra Region', 'Ashanti Region', None], dtype=object)

In [67]:
amenities_df.Category.unique()

array(['Senior high school', 'School', 'High school', 'Middle school',
       'International school', 'Educational institution',
       'Primary school', 'Private educational institution',
       'Elementary school', 'Technical', 'Catholic', 'Catholic school',
       'Higher secondary school', "Girls' high school", 'Church',
       'Non-denominational church', 'Church of Christ', 'Catholic church',
       'Presbyterian church', 'Methodist church', 'Parish',
       'Anglican church', 'Baptist church', 'Gospel church',
       'Apostolic church', 'Pentecostal church',
       'Church of Jesus Christ of Latter-day Saints', 'Christian church',
       'Seventh-day Adventist church', 'Church of the Nazarene',
       'Catholic cathedral', 'Evangelical church', 'Place of worship',
       'Congregation', 'United Church of Christ',
       'Assemblies of God church', 'Recruiter', 'Chapel', 'Hospital',
       'Government hospital', "Children's hospital",
       'Specialized hospital', 'University hospital', 'Medical Center',
       None, 'Private hospital', 'Plastic surgery clinic',
       'General hospital'], dtype=object)

In [68]:
from datetime import datetime
amenities_df["Date"]=datetime.today().date()

In [69]:
amenities_df.head(5)

,Name,Address,Category,Rating,Rate,Region,Date
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra Region,2024-07-11
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra Region,2024-07-11
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra Region,2024-07-11
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11

In [70]:


import numpy as np
conditions = [
    amenities_df["Category"].str.contains("school|institution", case=False, na=False),
    amenities_df["Category"].str.contains("church|chapel|worship|congregation", case=False, na=False),
    amenities_df["Category"].str.contains("hospital|medical center|clinic", case=False, na=False),
]

choices = [
    "School",
    "Church",
    "Hospital",
]

# Apply conditions using numpy select
amenities_df["Type"] = np.select(conditions, choices, default="Other")

In [71]:
amenities_df

,Name,Address,Category,Rating,Rate,Region,Date,Type
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra Region,2024-07-11,School
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra Region,2024-07-11,School
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra Region,2024-07-11,School
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11,School
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11,School
...,...,...,...,...,...,...,...,...
98,"Marie Stopes Clinic, Santasi - Kumasi","Santasi Round About, Dr. Kuffuor Bypass, Kumasi",Hospital,3.7,Medium,Ashanti Region,2024-07-11,Hospital
99,Rabito Clinic Kumasi,"111 Melcom Road, Kumasi",Hospital,3.9,Medium,Ashanti Region,2024-07-11,Hospital
100,Alternative medicine specialist Hospital,Kumasi,Hospital,4.5,High,Ashanti Region,2024-07-11,Hospital
101,Mary Pomaa Memorial Clinic,Kumasi,Hospital,5.0,High,Ashanti Region,2024-07-11,Hospital
102,Anwiam Clinic Annex,Kumasi,Hospital,3.5,Medium,Ashanti Region,2024-07-11,Hospital

In [72]:
amenities_df.head(5)

,Name,Address,Category,Rating,Rate,Region,Date,Type
0,Odorgonno Secondary School,"Anyaa-Awoshie Rd, Accra",Senior high school,4.2,High,Greater Accra Region,2024-07-11,School
1,Accra Girls Senior High School,"Olusegun Obasanjo Wy, Accra",Senior high school,4.3,High,Greater Accra Region,2024-07-11,School
2,Accra Academy,"Dr. Busia Hwy, Accra",Senior high school,4.5,High,Greater Accra Region,2024-07-11,School
3,St. Mary's Senior High School,"GQPG+8QC, Nii Tackie Owuowuo St, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11,School
4,Labone Senior High School,"Josiah Tongoogari Link, Accra",Senior high school,4.4,High,Greater Accra Region,2024-07-11,School

In [73]:
new_schema = 'gold'
new_table_name = 'MG_Fact_Amenities'

# Write DataFrame to the new table in the specified schema in the database
amenities_df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to gold.MG_Fact_Amenities successfully.