In [82]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
pop_history = 'silver.MG_Population_History'
pop_ghana = 'silver.Ps_Population_Ghana'
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query1 = f"SELECT * FROM {pop_history}"
query2 = f"SELECT * FROM {pop_ghana}"

# Execute the query and load the data into a DataFrame
pop_history_df = pd.read_sql(query1, engine)
pop_ghana_df = pd.read_sql(query2, engine)

In [83]:
pop_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      102 non-null    object
 1   Date        102 non-null    datetime64[ns]
 2   Population  72 non-null     float64
 3   Year        102 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 3.3+ KB

In [84]:
pop_ghana_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      119 non-null    object
 1   Date        119 non-null    object
 2   Population  89 non-null     float64
dtypes: float64(1), object(2)
memory usage: 2.9+ KB

In [85]:
pop_ghana_df.head(5)

          Region        Date  Population
0  Western North  2021-01-01    880921.0
1        Western  2021-01-01   2060585.0
2          Volta  2021-01-01   1659040.0
3     Upper West  2021-01-01    901502.0
4     Upper East  2021-01-01   1301226.0

In [86]:
pop_ghana_df["Date"]=pd.to_datetime(pop_ghana_df["Date"])

In [87]:
pop_ghana_df["Population"]=pd.to_numeric(pop_ghana_df["Population"],errors="coerce")

In [88]:
pop_ghana_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      119 non-null    object
 1   Date        119 non-null    datetime64[ns]
 2   Population  89 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 2.9+ KB

In [89]:
pop_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      102 non-null    object
 1   Date        102 non-null    datetime64[ns]
 2   Population  72 non-null     float64
 3   Year        102 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 3.3+ KB

In [90]:
pop_ghana_df["Year"]=pop_ghana_df["Date"].dt.year

In [91]:
pop_history_df.head(5)

          Region       Date  Population  Year
0  Western North 2021-01-01    880921.0  2021
1        Western 2021-01-01   2060585.0  2021
2          Volta 2021-01-01   1659040.0  2021
3     Upper West 2021-01-01    901502.0  2021
4     Upper East 2021-01-01   1301226.0  2021

In [92]:
pop_ghana_df.head(5)

          Region       Date  Population  Year
0  Western North 2021-01-01    880921.0  2021
1        Western 2021-01-01   2060585.0  2021
2          Volta 2021-01-01   1659040.0  2021
3     Upper West 2021-01-01    901502.0  2021
4     Upper East 2021-01-01   1301226.0  2021

In [93]:
population_df=pd.concat([pop_history_df,pop_ghana_df])

In [94]:
population_df

            Region       Date  Population  Year
0    Western North 2021-01-01    880921.0  2021
1          Western 2021-01-01   2060585.0  2021
2            Volta 2021-01-01   1659040.0  2021
3       Upper West 2021-01-01    901502.0  2021
4       Upper East 2021-01-01   1301226.0  2021
..             ...        ...         ...   ...
114       Northern 2024-07-09   2275388.0  2024
115       Savannah 2024-07-09    643142.0  2024
116     North East 2024-07-09    651079.0  2024
117     Upper East 2024-07-09   1272066.0  2024
118     Upper West 2024-07-09    878824.0  2024

[221 rows x 4 columns]

In [95]:
population_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 221 entries, 0 to 118
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      221 non-null    object
 1   Date        221 non-null    datetime64[ns]
 2   Population  161 non-null    float64
 3   Year        221 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 8.6+ KB

In [96]:
population_df.nunique()

Region        17
Date           7
Population    89
Year           7
dtype: int64

In [97]:
population_df.Region.unique()

array(['Western North', 'Western', 'Volta', 'Upper West', 'Upper East',
       'Savannah', 'Oti', 'Northern', 'North East', 'Greater Accra',
       'Eastern', 'Central', 'Bono East', 'Bono', 'Ashanti', 'Ghana',
       'Ahafo'], dtype=object)

In [98]:
population_df

            Region       Date  Population  Year
0    Western North 2021-01-01    880921.0  2021
1          Western 2021-01-01   2060585.0  2021
2            Volta 2021-01-01   1659040.0  2021
3       Upper West 2021-01-01    901502.0  2021
4       Upper East 2021-01-01   1301226.0  2021
..             ...        ...         ...   ...
114       Northern 2024-07-09   2275388.0  2024
115       Savannah 2024-07-09    643142.0  2024
116     North East 2024-07-09    651079.0  2024
117     Upper East 2024-07-09   1272066.0  2024
118     Upper West 2024-07-09    878824.0  2024

[221 rows x 4 columns]

In [99]:
population_df.Region.nunique()

17

In [108]:
population_df["Date"]=population_df["Date"].dt.date

In [110]:
population_df.drop(population_df[population_df['Region'] == 'Ghana'].index, axis=0, inplace=True)

In [111]:
population_df.Region.unique()

array(['Western North', 'Western', 'Volta', 'Upper West', 'Upper East',
       'Savannah', 'Oti', 'Northern', 'North East', 'Greater Accra',
       'Eastern', 'Central', 'Bono East', 'Bono', 'Ashanti', 'Ahafo'],
      dtype=object)

In [116]:
population_df=population_df.sort_values(by="Year")

In [117]:
new_schema = 'gold'
new_table_name = 'MG_Fact_Population'

# Write DataFrame to the new table in the specified schema in the database
population_df.to_sql(new_table_name, engine, schema=new_schema, if_exists='replace', index=False)

print(f"Data written to {new_schema}.{new_table_name} successfully.")

Data written to gold.MG_Fact_Population successfully.